### ISSUE TITLE
Server Options for "UDP Plugin Local Port" and "UDP Plugin Address".

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#126]
For some reason it doesn't take the values ​​recorded in "Server Options" for "UDP Plugin Local Port" and "UDP Plugin Address".
Random values ​​appear in the C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\server\cfg\server_cfg.ini 

![creenshot11](https://user-images.githubusercontent.com/48275749/53865524-2a7a9400-3fce-11e9-8d4e-fbc5b8ea7221.jpg)
![creenshot12](https://user-images.githubusercontent.com/48275749/53865931-1daa7000-3fcf-11e9-98bd-dbd3fff4d10d.jpg)

**Comment by cj123** [comment]
Hi!

This is actually an intentional trick that server manager does. Server manager itself uses the UDP plugin setup within Assetto Corsa Server. When a race starts, it finds some open ports and sets those in the assetto corsa config (as you've screenshotted above).

It listens for UDP messages for things such as live timings, championship information, etc. But then what it does is to forward its messages to the ports you specified in the settings (as shown in the top screenshot). 

I'm aware of an issue with this, as reported in #119 (sending messages to assetto corsa server via UDP currently seems to not work). I'm working on a more stable fix for this that will hopefully enable use of other plugins such as kissmyrank without any issues.

You should see this fix in the coming days.

**Comment by luismercury** [comment]
In agreement,

My idea is to continue using sTracker and for this reason it is the query.

**Comment by luismercury** [comment]
Good
