### ISSUE TITLE
LOCKED_ENTRY_LIST vs PICKUP_MODE

### ISSUE THREAD

**Issue by mike855** [cj123/assetto-server-manager#271]
Hello!

The locked entry list does not work. The Official Kunos FAQ is not up to date and is wrong.

For a locked entry list : 

LOCKED_ENTRY_LIST must be =0 (always 0, this parameter don't do anything now)
PICKUP_MODE=0

Edit : Forgot to say that PICKUP_MODE is at 0 in JSON file, but not in server_cfg.ini when the session is started

**Comment by cj123** [comment]
re-opening this for further discussion, as we're seeing some strange issues that I can only think must be related to this change:

@mike855 if you have any insight on these please chime in, we're just trying to figure out the best settings to use per each scenario.

I'm thinking that there are a couple of things that definitely need doing here:

1. Remove 'Locked Entry List' button entirely, if it is the case that this option does not work (and I think we **definitely need to verify this**), there should be no reference to it in the web UI. That means that probably the 'Locked Entry List' button needs renaming to 'Pickup Mode' and needs a thorough explanation so that people don't get as confused as I am right now!
2. Deprecate LockedEntryList in the config ini struct, remove any references to it. It will default to 0 (OFF).
3. Revisit the need to enable/disable pickup mode for Championship Events/Looped Practices. I'll list the issues we're seeing below:
   - Looped practice sessions no longer allow players to progress to the next session. 
  Speaking to @CaptainCondescending about this: 
     >joining a server with pickup mode "books" you on the server
     >so maybe because of that, im not "booked" in the next session
     >i have to rejoin
   - Looped practice Live Timings seem to not show previous sessions results anymore.

I think the only thing that needs changing here to fix point 3 is that Looped Practices must always have Pickup Mode ON (i.e. 1 in the ini file). I don't know that for sure though.


However, if we find that Locked Entry List does in fact work as a best fit for most championship events/practice sessions, I recommend we undo the changes which switched them to use Pickup Mode, make pickup mode an option available in the Custom Race form and let users decide for themselves!


I plan on making some time to test these things thoroughly this weekend, and I'll post my results here.

**Comment by mike855** [comment]
You are right, in booking mode you are kicked at the end of the last session.

For our championships we are doing this : 

Pickup mod to 1 for the practice loop and then pickup mode 0 the day of the race with practice/qualify/race.

With pickup mode at 1 we can all train on the server, our skin are random but this is not a problem)

Sometime we also just make the server open without steam id in entry list the days between the races to allow other player to play with us

**Comment by cj123** [comment]
>Remove 'Locked Entry List' button entirely, if it is the case that this option does not work (and I think we definitely need to verify this), there should be no reference to it in the web UI. That means that probably the 'Locked Entry List' button needs renaming to 'Pickup Mode' and needs a thorough explanation so that people don't get as confused as I am right now!

Perhaps this should be:

"Clarify Locked Entry List" button with help text, including a description that it is infact using Pickup Mode, that looped sessions kick you out at the end.

**Comment by mike855** [comment]
Locked entry list works, but the skins are assigned randomly from those in the entry list like on open server. I thinks it is usefully for someone :)

**Comment by WraithStar** [comment]
There is a very important thing to note about pickupMode: it makes the server crash at the end of race 1 if used in an event with 2 races.
This is a bug of Assetto Corsa and of course we can do nothing about this
