### ISSUE TITLE
recurring scheduled events

### ISSUE THREAD

**Issue by germanrcuriel** [cj123/assetto-server-manager#344]
Is there a chance to have scheduled races to be repeated in a daily or weekly basis, for example?

That would be pretty awesome to have some kind of SRS :)

**Comment by cj123** [comment]
I hadn’t considered that! I suppose we could use recurrence rules to do
this fairly easily.

On 24 May 2019, at 20:00, Germán Robledo <notifications@github.com> wrote:

Is there a chance to have scheduled races to be repeated in a daily or
weekly basis, for example?

That would be pretty awesome to have some kind of SRS :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cj123/assetto-server-manager/issues/344?email_source=notifications&email_token=AACK5OJADMJ2TASEQE62TY3PXA3OFA5CNFSM4HPR7L42YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GVYW4TQ>,
or mute the thread
