### ISSUE TITLE
ACC?

### ISSUE THREAD

**Issue by cheesegrits** [cj123/assetto-server-manager#461]
Big ask, I know, but any plans to extend this to allow for ACC?

I'm just doing some "forward planning" on how to run some regularly scheduled ACC races for my league (ACRL).

**Comment by Hecrer** [comment]
We actually have a working version for ACC, but it is very limited and almost completely untested.

Unfortunately ACC is a lot more locked down than AC was and (at least when we were working on it, just after release) didn't even let us access results files. Because of this most of the core Server Manager features wouldn't be possible to implement.

The scheduled and recurring race features would work (I think scheduling does already), but at this point we're not investing any time in it, and it would take a decent amount of work to get everything stable. We might pick the project up again in the future with enough interest though.

**Comment by cheesegrits** [comment]
Right now I'm mostly just interested in the race scheduling.

We decided to punt on using ACC for our next GT3 league season for now, but I'd like to run some regularly scheduled "community" ACC races just for fun. Can't remember if I mentioned elsewhere, but I do the provisioning for the ACRL league.  And it'd be nice to be able to automate those ACC races. No entry lists, no need to post process results. Just fire races up on a schedule. And, as per my other request, send reminders to Discord. :) 

Apparently 1.0.7 has improved the results JSON. But that was indeed one of the things that made us decide last month that it wasn't ready for league use yet. We'll take another look early next year.

**Comment by cheesegrits** [comment]
@Hecrer would you mind making the ACC version available on github?  Even if all it does atm is start races, that'd be useful for me, and I'd be happy to put some effort into getting other features working.

**Comment by Hecrer** [comment]
We've been discussing this and we're not planning to release what we have so far. Apologies for that but the project doesn't meet our standards at the moment and if we release it people will expect support and functionality that just isn't there.

It also doesn't work with the most recent version of ACC, and presumably will need constant upkeep to follow the development of ACC.

Thanks for showing that there is some interest though, as ACC grows our attention may shift back over to it, we'll just have to see.

**Comment by cheesegrits** [comment]
I understand.

We (ACRL) put a lot of effort this year into evaluating it, to see if we want to switch our main GT3 seasons over to it.  We decided it's not ready for prime time yet, but we're going to revisit it at the start of next year.  Two of the core ACC devs are ACRL members, and we have a private channel with them on our Discord, so we are privy to some of the roadmap, and we're fairly sure it'll be usable by then.

So one way or another, I'll have to put a lot of effort into provisioning for ACC, starting early next year.  And I'd rather put the effort in on an ACC-centric server-manager than rolling my own from scratch.
