### ISSUE TITLE
Remove championship entrant

### ISSUE THREAD

**Issue by Hecrer** [cj123/assetto-server-manager#509]
In open championships you can end up with tons of entrants with only one event completed. Allow admins to remove people in order to clean the page up a bit

**Comment by cj123** [comment]
I think the problem here is having to scroll far past a lot of entrants to get to the interesting bit of a championship. I'm not sure that the solution is allowing admins to delete entrants. Perhaps we could set a max-height on the points table at a sensible value (e.g. 20 or 30 entrants) and then make the other entrants visible by scrolling?

**Comment by cj123** [comment]
fixed by #573
